// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NintendoStore.Models;

namespace NintendoStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200406201737_newRow")]
    partial class newRow
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NintendoStore.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Mario Games"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "The Legend of Zelda Games"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Donkey Kong Games"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Nintendo Favorites"
                        });
                });

            modelBuilder.Entity("NintendoStore.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsonSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GameId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            CategoryId = 1,
                            Description = "Keep Cool with Mario",
                            ImageThumbnailUrl = "\\Images\\MarioSunshine.png",
                            ImageUrl = "\\Images\\MarioSunshine.png",
                            IsInStock = true,
                            IsonSale = true,
                            Name = "Super Mario Sunshine",
                            Price = 50.00m
                        },
                        new
                        {
                            GameId = 2,
                            CategoryId = 2,
                            Description = "Save Hyrule",
                            ImageThumbnailUrl = "\\Images\\OcarinaThumbnail.png",
                            ImageUrl = "\\Images\\LegendofZelda.png",
                            IsInStock = true,
                            IsonSale = true,
                            Name = "The Legend of Zelda, Ocarina of Time",
                            Price = 40.00m
                        },
                        new
                        {
                            GameId = 3,
                            CategoryId = 3,
                            Description = "get Bananas",
                            ImageThumbnailUrl = "\\Images\\DKTropicalThumbnail",
                            ImageUrl = "\\Images\\DonkeyTropical.jpg",
                            IsInStock = true,
                            IsonSale = true,
                            Name = "Donkey Kong Country: Tropical Freeze",
                            Price = 40.00m
                        });
                });

            modelBuilder.Entity("NintendoStore.Models.Game", b =>
                {
                    b.HasOne("NintendoStore.Models.Category", "Category")
                        .WithMany("Games")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
